### ISSUE TITLE
Strange message when using

### ISSUE THREAD

**Issue by dorel14** [brucemcpherson/VbaGit#5]
Hello 
I try to use vbagit and i have thismessage when sending to git
""didn't find repo info file..." and i have no "FILES.INFO" in my local folder .

**Comment by brucemcpherson** [comment]
I think you have got past this now .. please give an update

**Comment by dorel14** [comment]
With VGSettings.init(Nothing)
            With .add("EXTRACT")
                .add "TO", "C:\Users\caen\Documents\GitHub\test\"

Now my folders and sub folders are   are well  formatted  but when i do git(), i have this error in the 

Public Function JSONParse(s As String, Optional jtype As eDeserializeType, Optional complain As Boolean = True) As cJobject
    Dim j As New cJobject
    Set JSONParse = j.init(Nothing).parse(s, jtype, complain)
    j.tearDown
End Function

**Comment by dorel14** [comment]
after your answers on G+ , it works really fine 
thx
